# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='added_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
