# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_company_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_of_employees',
            field=models.CharField(choices=[('1-20', '1-20'), ('21-50', '21-50'), ('51-100', '51-100'), ('>100', '>100')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Education', 'Education')], default='it', max_length=10),
        ),
    ]
