# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_auto_20160404_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmuser',
            name='added_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
