# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_crmuser_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmuser',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_app_crmuser_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
